### ISSUE TITLE
Unexpected Exception: KeyError 'uuid'

### ISSUE THREAD

**Issue by bigmacd** [Phil997/pydantic-sqlite#8]
I noticed in the examples of the README.md that the classes have a uuid.  However, my model does not:

`class hprItem(BaseModel):
    s_id: str
    start_time: str
    end_time: str
    recurring: str
    c_id: int
    s_id: int
    t_id: str`

When I try to add an instance of the above class to the database, it throws a keyerror.

Is there a requirement that your pydantic models have to have a uuid?

**Comment by Phil997** [comment]
Hello,

I am using sqlite-utils.Database and this need a primary key "pk" as identifier. So you need an identifierin your models. I am using a uuid for this. If you want to use anything other than uuid as p key you can set it with the param `pk` when adding a model.

https://github.com/Phil997/pydantic-sqlite/blob/d52d0f42045c90b47a8e6987ec60dd071444f427/pydantic_sqlite/_core.py#L83


I hope it helps.
